# Generated by Django 5.2.1 on 2025-05-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='stripe_payment_intent',
            new_name='instamojo_payment_request_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='instamojo_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
