# Generated by Django 5.2.1 on 2025-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_stripe_payment_intent_orderdetail_instamojo_payment_request_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='instamojo_payment_request_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='instamojo_payment_id',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
