# Generated by Django 5.2.1 on 2025-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_stripe_payment_intent_orderdetail_instamojo_payment_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='instamojo_payment_request_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
